package cn.sifangguan.ota.worker.sprint2.contract;

public enum ConnectorContractApprovalReason {
    CONNECTOR_CONTRACT_BASELINE_UNAVAILABLE,
    CONNECTOR_CONTRACT_BASELINE_MISSING,
    CONNECTOR_CONTRACT_BASELINE_REVOKED,
    CONNECTOR_CONTRACT_FINGERPRINT_ALGORITHM_UNSUPPORTED
}
