package cn.sifangguan.ota.worker.sprint2.validation;

public enum CollectionResultRejectionReason {
    CONNECTOR_RESULT_STATUS_QUALITY_INVALID,
    CONNECTOR_RESULT_WATERMARK_INVALID,
    CONNECTOR_RESULT_ENVELOPE_SCOPE_MISMATCH,
    CONNECTOR_RESULT_ENVELOPE_SOURCE_MISMATCH,
    CONNECTOR_RESULT_EVIDENCE_INVALID,
    CONNECTOR_RESULT_IDEMPOTENCY_INVALID,
    CONNECTOR_RESULT_SCHEMA_INVALID,
    CONNECTOR_RESULT_TRUSTED_TIME_INVALID
}
