package cn.sifangguan.ota.contracts.connector;

public enum ConnectorCapability {
    PMS_BUSINESS_DATE,
    BOOKING_EVENTS,
    CANCELLATION_EVENTS,
    INVENTORY_BY_ROOM_TYPE,
    INVENTORY_BY_SELL_PRODUCT,
    ROOM_REVENUE_DETAIL,
    ROOM_REVENUE_AGGREGATE,
    HOURLY_ROOM_REVENUE,
    OVERNIGHT_SOLD,
    EFFECTIVE_SELLABLE_TOTAL,
    SOURCE_UPDATED_AT,
    BROWSER_SESSION_AUTH,
    OFFICIAL_EXPORT_PARSE
}
