package cn.sifangguan.ota.browsersession;

public enum BrowserSessionErrorCode {
    INVALID_SESSION_SCOPE("BSH_INVALID_SESSION_SCOPE"),
    SESSION_SCOPE_MISMATCH("BSH_SESSION_SCOPE_MISMATCH"),
    INVALID_STATE_TRANSITION("BSH_INVALID_STATE_TRANSITION"),
    NON_MONOTONIC_TRANSITION_TIME("BSH_NON_MONOTONIC_TRANSITION_TIME"),
    INTERACTIVE_LOGIN_REQUIRED("BSH_INTERACTIVE_LOGIN_REQUIRED"),
    SESSION_EXPIRING("BSH_SESSION_EXPIRING"),
    REAUTH_REQUIRED("BSH_REAUTH_REQUIRED"),
    SESSION_REVOKED("BSH_SESSION_REVOKED"),
    INVALID_TARGET("BSH_INVALID_TARGET"),
    INVALID_REQUEST_CONTRACT("BSH_INVALID_REQUEST_CONTRACT"),
    TARGET_NOT_ALLOWLISTED("BSH_TARGET_NOT_ALLOWLISTED"),
    INVALID_RESOLVED_ADDRESS("BSH_INVALID_RESOLVED_ADDRESS"),
    RESOLVED_ADDRESS_REQUIRED("BSH_RESOLVED_ADDRESS_REQUIRED"),
    NON_PUBLIC_ADDRESS_FORBIDDEN("BSH_NON_PUBLIC_ADDRESS_FORBIDDEN"),
    UNKNOWN_CONFIGURATION_KEY("BSH_UNKNOWN_CONFIGURATION_KEY");

    private final String code;

    BrowserSessionErrorCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
